project:
  type: website
  output-dir: _site

website:
  title: "R y Python para Ciencias Biol칩gicas"
  description: "Aprende R y bioestad칤stica con contenido interactivo"
  # repo-url: https://github.com/santi-rios/R_interactivo_ejecutar
  repo-actions: [issue]
  issue-url: https://github.com/santi-rios/R_estadistica_cienciasBiologicas/issues
  site-url: https://orcaasesina.com/
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Mas cursos** de R, Python, Git y bioinform치tica en [orcaasesina.com](https://orcaasesina.com)."
    type: primary
    position: below-navbar
  page-navigation: true
  page-footer: 
    left: "Copyright 2025, Santiago R칤os" 
    right: 
      - icon: github
        href: https://github.com/santi-rios
      - icon: globe
        href: https://santi-rios.github.io/
  # navbar:
  #   background: "#ded6ea"
  #   search: true
  #   logo: images/logo.png
  #   left:
  #     - text: "游 Inicio"
  #       href: index.qmd
  #   # contents: 
  #   #   - href: index.qmd
  #   #     title: "Inicio"
  #     - text: "游눹 1.-Introducci칩n"
  #       href: sections/00-presentacion.qmd
  #     - text: "游닄 2.-Datos"
  #       href: sections/03-importar-limpieza.qmd
      # - section: "Introducci칩n a Estad칤stica"
      #   contents:
      #     - sections/02-estadistica.qmd
      # - section: "Modelado Estad칤stico"
      #   contents:
      #     - sections/03-estadisticall.qmd
      # - section: "Estad칤stica Avanzada"
      #   contents:
      #     - sections/04-estadisticalll.qmd
  # navbar:
  #   background: primary
  #   search: true
  #   title: false
  #   logo: images/logo.pngsections/02-programacion
  #   background: "Logo"
  #   tools:
  #     - search: true
  #     - icon: "fa-solid fa-moon"
  #       href: "
  #         - text: "Dark"
  #         - text: "Light"
      # - icon: twitter
      #   href: https://twitter.com
      # - icon: github
      #   menu:
      #     - text: Source Code
      #       href:  https://code.com
      #     - text: Report a Bug
      #       href:  https://bugs.com  
  #   left:
  #     - text: "Home"
  #       href: index.qmd
  #     - talks.qmd
  #     - about.qmd


format:
  html:
    theme: superhero
      # light: pulse
      # dark: superhero
    respect-user-color-scheme: true
    toc: true
    toc-depth: 2
    toc-location: right
    toc-title: "Contenido"
    lang: es
  live-html: 
      toc: true
      # theme: simple
      # scrollable: true
      toc-depth: 2
      toc-title: Contenido de la Lecci칩n
      # progress: true
      # slide-number: true
      lang: es
      # logo: "https://cran.r-project.org/Rlogo.svg"
